name: github release
on:
  push:
    paths-ignore:
      - README.md
    branches:
      - master
jobs:
  tox-ci:
    uses: QualiSystems/.github/.github/workflows/package-tox-py.yml@master
    with:
      pre-commit-py-version: "3.9"
      build-py-version: "3.9"
      tests-py-version: "3.9"
  pypi-deploy:
    needs: tox-ci
    uses: QualiSystems/.github/.github/workflows/package-github-release.yml@master
